name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore NuGet packages
        run: dotnet restore encriptionapi.sln

      - name: Build the solution
        run: dotnet build encriptionapi.sln -c Release

      - name: Run tests
        run: dotnet test ./encriptionapi.csproj --configuration Release --logger "trx;LogFileName=test-results.trx"

      - name: Publish the project
        run: |
          dotnet publish ./encriptionapi.csproj -c Release -o ./publish
          ls -l ./publish  # Verify the .runtimeconfig.json file is present

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS
        run: |
          # Create a ZIP file from the published application
          zip -r EncryptionApi.zip ./publish/*

          # Upload the ZIP file to S3
          aws s3 cp EncryptionApi.zip s3://deploybucket-log/

          # Create a new application version
          VERSION_LABEL=${{ github.sha }}  # Use commit SHA as version label
          aws elasticbeanstalk create-application-version \
            --application-name Appdeploy \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket="deploybucket-log",S3Key="EncryptionApi.zip"

          # Update the environment to use the new version
          aws elasticbeanstalk update-environment \
            --environment-name Appdeploy-env \
            --version-label $VERSION_LABEL
